# Generated by Django 3.2.6 on 2021-08-27 20:29

from django.db import migrations, models
import django.db.models.deletion
import jobslist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('T', 'Tree'), ('H', 'Hedge'), ('M', 'Mixed')], max_length=1)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField(default=jobslist.models.get_deadline)),
                ('completed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobslist.customer')),
            ],
        ),
    ]
