# Generated by Django 3.2.6 on 2021-09-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='completed',
        ),
        migrations.AddField(
            model_name='job',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
