# Generated by Django 3.2.6 on 2021-09-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist', '0002_auto_20210920_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='flexibility',
            field=models.CharField(choices=[('E', 'Easy'), ('S', 'Standard'), ('A', 'Awkward')], default='S', max_length=1),
        ),
    ]
