# Generated by Django 3.2.6 on 2021-10-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobslist', '0003_job_flexibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
